# Author: Kathryn Bernard
# Purpose: 
# Inputs: Two files - the clean datasets generated by script 02_data_cleaning.R

## Setup
# Load packages
library(tidyverse)

# Read in data
parcel_data <- read.csv("data/950_parcel_habitat_clean.csv")
woody_data <- read.csv("data/950_woody_habitat_clean.csv")

# Separate our group's lake - Big Arbor Vitae Lake
arbor_parcel <- parcel_data %>% filter(LAKE_NAME == "Big Arbor Vitae Lake")
arbor_woody <- woody_data %>% filter(LAKE_NAME == "Big Arbor Vitae Lake")


# Variables of interest
# Shoreline vegetation - shrubs/herbs/manicured lawn
# Erosion control structures vs. risks to erosion like channels/stairs/etc
# Aquatic vegetation - floating/emergent