# Author: Kathryn Bernard
# Purpose:
# Inputs: Two files - the clean datasets generated by script 02_data_cleaning.R

## Setup
# Load packages
library(tidyverse)
library(gridExtra)

# Read in data
parcel_data <- read.csv("data/950_parcel_habitat_clean.csv")
woody_data <- read.csv("data/950_woody_habitat_clean.csv")

# Separate our group's lake - Big Arbor Vitae Lake
arbor_parcel <-
  parcel_data %>% filter(LAKE_NAME == "Big Arbor Vitae Lake")
arbor_woody <- woody_data %>% filter(LAKE_NAME == "Big Arbor Vitae")


## Developed vs non developed parcels

nondeveloped_ids <-
  c(
    "2-2562-02",
    "2-2562-01",
    "2-2562",
    "2-2556",
    "2-2553-06",
    "2-2565",
    "2-2566",
    "2-2582",
    "2-2597",
    "2-2648"
  )

arbor_parcel$DEVELOPED <-
  !arbor_parcel$PARCELID %in% nondeveloped_ids

arbor_parcel %>%
  group_by(DEVELOPED) %>%
  summarize(
    mean_canopy = mean(CANOPY_PCT),
    mean_erosion = mean(GREAT_ERO_LEN),
    mean_float = mean(FLOATING_VEG_PRES),
    mean_EMERG = mean(EMERGENT_VEG_PRES)
  )


# parcel drilldown
## 2-2686-16
# land: lots of structures, lots of manicured lawn, medium canopy, few shrubs/herbs
# water: lots of structures, some veg
# erosion: lots of control structures, no concerns, no actual erosion
parcel_one <- arbor_parcel[arbor_parcel$STRUCTURES_TOTAL==max(arbor_parcel$STRUCTURES_TOTAL),]

# 2-2562-02
# land: lots of canopy and shrub/herb, no structures
# water: no structures, no veg
# erosion: a lot of erosion (from the notes), channel flow present but no great-ero-len documented
parcel_two <- arbor_parcel[22,]

#2-2649
# land: lots of canopy, lots of shrub/herb, no structures
# water: has veg, has aquatic structures
# erosion: no concerns, some controls
parcel_three <- arbor_parcel[arbor_parcel$PARCELID=="2-2649",]

# create a small dataframe with just parcels of interest
parcel_dd <- arbor_parcel %>% filter(PARCELID==parcel_one$PARCELID | PARCELID==parcel_two$PARCELID | PARCELID==parcel_three$PARCELID)